### ISSUE TITLE
议题征集

### ISSUE THREAD

**Issue by Yexiaoxing** [AOSC-Dev/aoscc-2015#1]
AOSCC 2015 将在 2015 年 7 月 11 日 ~ 2015 年 7 月 13 日（初定）在深圳召开，现向各社区成员征集相关议题。

---

Update 20150627: 2015.7.11 - 2015.7.13

**Comment by netarmy** [comment]
### 開源社羣開發入門教學
* 開坑指南
* 抗拖延指南
* 發佈指南
* 協作指南
* 幫助和支持指南

**Comment by MingcongBai** [comment]
1. AOSC OS4 发展方向辩论，主要是基于现有条件去讨论可能的方式。AOSC OS Core 是 AOSCC 前确立的计划，需确定 AOSC OS Core 衍生版本的 guideline 之类。
2. Autobuild 代码风格以及功能性讨论。
3. ABBS (AutoBuild Build System) 介绍，入门以及 AOSC OS4 打包手把手培训（可能的 CT 人员引入）。

来自 @YeXiaoxing 
1. 网站改版以及重构。
2. 邮件列表。
3. anthonos.org 域名邮箱。

**Comment by MingcongBai** [comment]
补充一下，ARM 以及其他架构移植可行性以及现实计划讨论。

@Icenowy

**Comment by jyhi** [comment]
1. 安同校园社团联盟 (AOSC SCU) 及其中各校园社团发展方向及方式讨论
2. 安同开始程序 (Anthon-Starter) 新版本 (0.2.5) 架构及发展方向讨论
   - 可能的更名：Anthon-Starter -> AST's Startup Toolkit

**Comment by bobcao3** [comment]
关于社区定位与目标的讨论
关于宣传与推广的讨论
关于下一次会议地点与时间的讨论

**Comment by bobcao3** [comment]
补充：（这个也算上吧）livekit及关于实现一个低学习成本系统的可能性

**Comment by MingcongBai** [comment]
AOSC OS4 编译规范调整（编译优化，Hardening 以及 LTO）。
- LTO，链接时优化

**Comment by bobcao3** [comment]
AOSC OS4 软件包规范

**Comment by MingcongBai** [comment]
将 Calamares 适配为 AOSC OS4（换句话就是简易安装支持） @bobcao3

**Comment by MingcongBai** [comment]
将 Calamares 适配为 AOSC OS4 的安装程序，并尝试降低安装门槛。

**Comment by bobcao3** [comment]
/ \
 |          真的非常不认为用Calamares做安装程式是好主意
 |

**Comment by MingcongBai** [comment]
@bobcao3 具体讨论不要在这里讨论

**Comment by MingcongBai** [comment]
受 @LionNatsu 委托…… 我直接 quote 的原话。
1. AOSCC上建议有演讲式（自备演示文档）发言部分。
2. 雨寒（我那只小伙伴）提出希望重新设计社区Logo，当然，保留同心圆的理念之类的……
   3.我有一个关于开源的（很可能是跨平台和设备的）界面设计框架的方案（类似Qt，具体的年会上说说吧），项目会比较大，我想在年会上和大家探讨一下。
3. 关于宣传的问题应该考虑一下，如海报和宣传视频。在大学里可能会有用：找一些技术人员？

**Comment by Artoria2e5** [comment]
## Bash 代码要求

Thanks for a certain Icenowy to inspire me so much in bash styling. Your bugs and artifacts are the greatest source of my knowledge in bash.
1. `grep -q` instead of `grep >/dev/null` (eliminate useless redirections)
   - Where possible, use internal `[[ "$string" =~ EREGEX ]]`.
2. `foo <<< "$bar" | baz` instead of `echo "$bar" | foo | baz` (readability)
3. `echo -n "$foo"` instead of `printf "$foo"` (avoids jaming with printf %'s)
4. Never use <code>`command`</code>.
5. Use early returns in sourced files and functions.
6. Use functions to restrict the scopes of variables.
   - Always local-ize the loop variables used in a function.
   - If bash regex matching is used, localize `BASH_REMATCH`.
7. Unset internal variables when the step is done.
8. Fuck internal `bool` usage.
9. Fuck reluctant names of shell libraries that would be used only internally, e.g. `abbsfoobar` in `abbs`.
10. Always use underscores to mark namespace usage, e.g. `abbs_foofunc`.
11. When necessary, use underscores(_) to split words.
12. At least document some input/output signature for your functions as comments.
13. Never assume too much in your code.\
14. Fuck `[ "x$foo" == "x" ]` for empty tests. Use `[ -z "$foo" ]` instead. ABS is NOT a bash style guide.
    - Likewise, use `[ "$foo" ]` instead of `[ "x$foo" != "x" ]`. This is tested to be safe with statements starting with `-`.
15. Fucking brain-trace seldom-used variables and eliminate them.
16. Fuck manual export and use `declare -x`.
17. Fuck nonsence `else true` / `else :` statements. Your Chinese teacher should have taught you what `if ! foo` is in Chinese.
18. Strip reluctant calls by using bash's builtin string manipulation.
19. Be wise with subshelling, like `$()` and `()`, since variables changes and break controls in subshell does not affect the outer shell.
20. When using eval, use `printf '%q '` or any wrapped variant of it to escape the parameters properly and stay safe from some attacks.

### 待定
1. Force `declare -i` for integer types.
2. Use ascii for globs, or use a temporary `en_US.UTF-8` environment?
3. Use `[[` instead of `[`, when
   - Always, or
   - Logical operations like `-a` (in `[[`, `&&`) is involved.
4. Avoid forking into subshells too much:
   - Use `{ { foo && bar; } || baz && midori; } || friendship` instead of `( (foo && bar) || baz && midori) || friendship`.
5. Avoid relying on `for i in $str` to expand groups of data and use `for i in "${arr[@]}"` instead, especially when we are dealing with filenames.
6. Use the style `(PATTERN)` for case patterns, so it looks balanced. This also fixes the issue when nesting `case` in `$()`. 

``` Bash
# common header
shopt -s extglob expand_aliases
# aliases for function scoping, ...

## UTIL
mkcomma(){ ((cnt++)) && echo -n "$COMMA"; }
```

``` Bash
#!/bin/bash
# foolib: lib of foo for bar module. See complete vario spec in bar.md chapter foo.
aosc_lib foolib
{ ((_baz_use_foo)) && cp --version | grep -q GNU; } || return 0

_baz_bar_loaded+='foo '
_baz_bar_variables+='fiberone grams_25 '
fibreone=42 grams25=bar # int, string

# "$@".foreach_withcomma(foo_genstr)
foo(){ for i; do foo_genstr "$i"; mkcomma; done; }

# foo_genstr: foo[_ver] -> foo=ver
foo_genstr(){
    local IFS=_ ver
    local arr=($1)
    # IF EMPTY REDUCTION: if [ "${arr[1]}" ]; then ver=${arr[1]}; else ver="$(getver "$1")"; fi
    ver="${arr[1]=$(getver "$1")}"
    # SED CALL REMOVAL: ver="$(sed 's/-/./g' <<< "$ver")"
    # VAR SET STRIPING: ver=${ver//-/.}; echo "${arr[0]}=$ver"
    echo "${arr[0]}=${ver//-/.}"
}
```

**Comment by Artoria2e5** [comment]
## Git Message 写作指南

现在的 commit log 超级乱。

## 代码中的 whitespace

据说 `}then{` 这种是审美观严重缺失？
如果有 IDE 调格式就用起来啊。

## 汉语和英语写作风格指北

为什么以及怎么做。基本都照着同名 repo 的来。

### 命令行交互写作

主要都是传统啦，``foo'` 你不用也得用。

## bash-misc: modern bash scripting

好吧我不会讲更多 Bash 的……如果哪天我写完了我那组 m4 我可能倒是真的要写 bash 教程。

### In-brain real-time abstraction

这是开玩笑，毕竟不能要求所有人都脑内装着团 IR……

## Detailed manual reading with texinfo

听说你们连 info 都不想开？

**Comment by Icenowy** [comment]
Bourne Again Shell指南
 Bourne and Bourne Infinitely Shell指北

from Galaxy SII HD

-------- 原始邮件 --------
发件人： Mingye Wang <notifications@github.com> 
日期: 2015/06/17  1:46 上午  (GMT+08:00) 
收件人： AOSC-Dev/aoscc-2015 <aoscc-2015@noreply.github.com> 
抄送： Icenowy Zheng <icenowy@outlook.com> 
主题： Re: [aoscc-2015] 议题征集 (#1) 
 
Git Message 写作指南

汉语和英语写作风格指北

**Comment by jyhi** [comment]
20150627：开始整理议题内容并加入议程。
后续添加视情况加入。

**Comment by 910JQK** [comment]
关于安装程序，我有一点想法。
现在使用拷贝 squashfs 的方法安装。这种方法虽然快，但是丧失了一定的可定制性。一个包一个包装虽然慢，但可以**让用户去选择自己偏好的软件包**，无需安装后再 Install XXX, Uninstall XXX, Reboot, 比较省心。
至于源的问题怎么办，可以网络安装，或者裁剪 livecd, 把包塞光盘里一部分（光盘源），剩下的要安装就从网上下载。

希望各位能考虑一下。

**Comment by MingcongBai** [comment]
你好，@910JQK

你的意思是一个 Base System 外加新增软件包的功能吗？

另外本地源的问题我个人有思考过，但是由于源的大小实际上远远超过 DVD 容量，甚至远远超过一张 DVD-9 的容量，所以暂时并没有什么头绪。
2015年6月29日 下午2:15于 "910JQK" notifications@github.com写道：

**Comment by bobcao3** [comment]
@MingcongBai 
We can hav DEV1,DVD2,DVD3and so on

**Comment by LionNatsu** [comment]
或许，评估包的使用人数（热门程度），然后进行DVD尺寸以内的遴选，这样可以一定程度上做到离线安装。

**Comment by MingcongBai** [comment]
@LionNatsu

Interestingly, Debian Installer uses "popularity-contest" module to do this trick. Exactly the same thought. 

Good job.

**Comment by MingcongBai** [comment]
Proposed a fill-up for the agenda, based on @lmy441900 's work.

**Comment by Artoria2e5** [comment]
@910JQK 我们实际上现在有实时取 apt/zypper 的朴dou素bi实现，但是 OS3 本来就没什么鸟。

@MingcongBai 哦……你是真不会只把一部分包……吗

---

我靠老白你对着那个 dpkg-scanpackage 看了这么久不会都没想到 mv 然后造吧？！

**Comment by MingcongBai** [comment]
还是建议到场讨论…… 我没想过这事儿

> @MingcongBai https://github.com/MingcongBai 哦……你是真不会只把一部分包……吗
